In [1]:
import numpy as np

In [2]:
integers_arr = np.arange(10)
integers_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
integers_sec_arr = np.arange(100,130)
integers_sec_arr

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129])

In [4]:
int_third_arr = np.arange(100,151,2)
int_third_arr

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124,
       126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150])

In [6]:
first_float_arr = np.linspace(10,20)
first_float_arr

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [7]:
second_float_arr = np.linspace(10,20,5)
second_float_arr

array([10. , 12.5, 15. , 17.5, 20. ])

In [8]:
first_rand_arr = np.random.rand(10)
first_rand_arr

array([0.88486401, 0.35232894, 0.3931383 , 0.65932314, 0.04898854,
       0.95723552, 0.53485009, 0.45236408, 0.64952163, 0.1055441 ])

In [9]:
second_rand_arr = np.random.rand(10,4)
second_rand_arr

array([[0.20574729, 0.73831611, 0.94818346, 0.87010854],
       [0.08392654, 0.75319884, 0.62674205, 0.37722829],
       [0.79691906, 0.96519771, 0.13219575, 0.47709025],
       [0.72156731, 0.31035044, 0.59041124, 0.13007131],
       [0.97892075, 0.49950275, 0.1192105 , 0.81864288],
       [0.52676075, 0.87830236, 0.84285307, 0.94414769],
       [0.28926952, 0.92555439, 0.29988288, 0.86757276],
       [0.5331169 , 0.72015002, 0.64770231, 0.40647576],
       [0.7325867 , 0.6078569 , 0.18013277, 0.49479068],
       [0.93238641, 0.5594991 , 0.82720145, 0.66425946]])

In [10]:
third_rand_arr = np.random.randint(0,100,20)
third_rand_arr

array([41, 84, 42, 66, 27, 41,  6, 18, 11, 58, 76, 73, 15, 11, 71, 13, 93,
       17, 33, 91], dtype=int32)